### PR TITLE
Fixing and more 1.18.2

### LINKED ISSUE #10: Version Placeholder is not working.
I think you have to replace this with `%version%`

### LINKED ISSUE #12: /gcteams create not working

### PR DESCRIPTION
**Pull request by Feier68**
Closes #12 #10

### CODE REVIEW

**Comment by kevinxdev** [comment]
@Feier68 please set empty string ("") if no world type is set: https://github.com/gigaclub/Builder-System-Plugin/blob/1.18.2/src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java#L97

File: src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java [hunk 1]
```diff
@@ -244,14 +212,14 @@ public boolean onCommand(CommandSender sender, Command command, String label, St
 
                             JSONObject user = users.getJSONObject(j);
 
-                            Player player11 = Bukkit.getPlayer(user.getString("name"));
-                            String player21 = player11.toString();
+                            UUID uuid = UUID.fromString(user.getString("mc_uuid"));
+                            OfflinePlayer player11 = Bukkit.getOfflinePlayer(uuid);
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java:215]: @Feier68 do not use numbers in variables. If you have duplicate variable names, assign the variable above and name the variables correctly.

File: src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java [hunk 2]
```diff
@@ -244,14 +212,14 @@ public boolean onCommand(CommandSender sender, Command command, String label, St
...
+                            String player21 = player11.getName();
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java:216]: @Feier68 do not use numbers in variables. If you have duplicate variable names, assign the variable above and name the variables correctly.

File: src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java [hunk 3]
```diff
@@ -244,14 +212,14 @@ public boolean onCommand(CommandSender sender, Command command, String label, St
...
                             StringBuilder res1 = new StringBuilder();
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java:217]: @Feier68 do not use numbers in variables. If you have duplicate variable names, assign the variable above and name the variables correctly.

File: src/main/java/net/gigaclub/buildersystemplugin/cache/WorldCache.java [hunk 4]
```diff
@@ -145,25 +152,26 @@ public void worldinfo(int iworld, Inventory inventory, int i, JSONArray worlds)
...
+        JSONArray users = world.getJSONArray("user_ids");
         for (int j = 0; j < users.length(); j++) {
 
             JSONObject user = users.getJSONObject(j);
 
-            Player player11 = Bukkit.getPlayer(user.getString("name"));
-            String player21 = player11.toString();
+            UUID uuid = UUID.fromString(user.getString("mc_uuid"));
+            OfflinePlayer player11 = Bukkit.getOfflinePlayer(uuid);
+            String player21 = player11.getName();
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/cache/WorldCache.java:150]: @Feier68 do not use numbers in variables. If you have duplicate variable names, assign the variable above and name the variables correctly.

File: src/main/java/net/gigaclub/buildersystemplugin/cache/WorldCache.java [hunk 5]
```diff
@@ -145,25 +152,26 @@ public void worldinfo(int iworld, Inventory inventory, int i, JSONArray worlds)
...
-        JSONArray users = world.getJSONArray("user_manager_ids");
+        JSONArray users = world.getJSONArray("user_ids");
         for (int j = 0; j < users.length(); j++) {
 
             JSONObject user = users.getJSONObject(j);
 
-            Player player11 = Bukkit.getPlayer(user.getString("name"));
-            String player21 = player11.toString();
+            UUID uuid = UUID.fromString(user.getString("mc_uuid"));
+            OfflinePlayer player11 = Bukkit.getOfflinePlayer(uuid);
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/cache/WorldCache.java:149]: @Feier68 do not use numbers in variables. If you have duplicate variable names, assign the variable above and name the variables correctly.

File: src/main/java/net/gigaclub/buildersystemplugin/cache/WorldCache.java [hunk 6]
```diff
@@ -145,25 +152,26 @@ public void worldinfo(int iworld, Inventory inventory, int i, JSONArray worlds)
...
+            String player21 = player11.getName();
             StringBuilder res1 = new StringBuilder();
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/cache/WorldCache.java:151]: @Feier68 do not use numbers in variables. If you have duplicate variable names, assign the variable above and name the variables correctly.

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/Navigator.java [hunk 7]
```diff
@@ -0,0 +1,164 @@
...
+
+        if (item == null) {
+            return;
+        } else {
+            ItemMeta meta = item.getItemMeta();
+            if (meta == null) {
+                return;
+            }
+        }
+        String taskl = "task_l" + this.taskGui.taskinv;
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/Navigator.java]: @Feier68 do not use numbers in variables. If you have duplicate variable names, assign the variable above and name the variables correctly.

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/Navigator.java [hunk 8]
```diff
@@ -0,0 +1,164 @@
...
+
+
+        }
+
+
+    }
+
+
+    @EventHandler
+    public void ClickInvCancel(InventoryClickEvent event) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/Navigator.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/Navigator.java [hunk 9]
```diff
@@ -0,0 +1,164 @@
...
+        ItemStack ProjectList = new ItemBuilder(api.getItemHead("32442")).setGui(true).addIdentifier("World_Opener").setDisplayName((ChatColor.BLUE + " your Project List")).setLore(this.worldGui.WorldloreList()).build();
+
+        inventory.setItem(10, TeamGui);
+        inventory.setItem(13, TaskList);
+        inventory.setItem(16, ProjectList);
+        player.openInventory(inventory);
+    }
+
+    @EventHandler
+    public void ClickEvent(InventoryClickEvent event) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/Navigator.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 10]
```diff
@@ -0,0 +1,193 @@
...
+public class TaskGui implements Listener {
+
+    public int invWatName = 0;
+    public Integer taskinv = 0;
+    public int taskID;
+    HeadDatabaseAPI api = new HeadDatabaseAPI();
+    Translation t = Main.getTranslation();
+    BuilderSystem builderSystem = Main.getBuilderSystem();
+    Boolean worldTypSelectoractiv = false;
+    String WorldTypeselectet;
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign variables in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 11]
```diff
@@ -0,0 +1,193 @@
...
+    ItemStack ON = new ItemBuilder(Material.GREEN_CONCRETE_POWDER).setGui(true).setDisplayName(ChatColor.GREEN + "ON").build();
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 UPPERCASE variables should have a final

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 12]
```diff
@@ -0,0 +1,193 @@
...
+    ItemStack OFF = new ItemBuilder(Material.RED_CONCRETE_POWDER).setGui(true).setDisplayName(ChatColor.RED + "OFF").build();
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 UPPERCASE variables should have a final

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 13]
```diff
@@ -0,0 +1,193 @@
...
+    ItemStack on;
+    ItemStack off;
+
+    public TaskGui() {
+        this.on = new ItemBuilder(api.getItemHead("9386")).setDisplayName((ChatColor.GREEN + "Activate")).setLore("").setGui(true).addIdentifier("on").build();
+        this.off = new ItemBuilder(api.getItemHead("9386")).setDisplayName((ChatColor.RED + "Deactivate")).setLore("").setGui(true).addIdentifier("off").build();
+    }
+
+    public ArrayList<String> TaskloreList() {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 14]
```diff
@@ -0,0 +1,193 @@
...
+        ArrayList<String> loreList = new ArrayList<>();
+        loreList.add(ChatColor.GOLD + "--------------");
+        loreList.add(ChatColor.GOLD + "Open Task List");
+        loreList.add(ChatColor.GOLD + "get your  Task");
+        loreList.add(ChatColor.GOLD + "--------------");
+        return loreList;
+    }
+
+    public void TaskGui(Player player) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 15]
```diff
@@ -0,0 +1,193 @@
...
+        Inventory inventory = Bukkit.createInventory(null, size, (ChatColor.GOLD + "Task Gui"));
+        for (int i = 0; i < size; i++) {
+            inventory.setItem(i, new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE).setDisplayName(" ").setGui(true).build());
+        }
+        inventory.setItem(10, new ItemBuilder(Material.PAPER).setGui(true).addIdentifier("task_list").setDisplayName("Task List").build());
+        inventory.setItem(size - 1, backtoMain);
+        player.openInventory(inventory);
+    }
+
+    public void TaskList(Player player, int index) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 16]
```diff
@@ -0,0 +1,193 @@
...
+        return loreList;
+    }
+
+    public ArrayList<String> createAsUserlore() {
+        ArrayList<String> loreList = new ArrayList<>();
+        loreList.add(ChatColor.GOLD + "Create Projeckt as User");
+        return loreList;
+    }
+
+    public void TaskSelect(Player player, int taskid) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 17]
```diff
@@ -0,0 +1,193 @@
...
+        int size = 9 * 1;
+        Inventory inventory = Bukkit.createInventory(null, size, ("Create a Projeckt"));
+        inventory.setItem(2, new ItemBuilder(api.getItemHead("9386")).setDisplayName((ChatColor.RED + "Create as Team")).setLore(createAsTeamlore()).setGui(true).addIdentifier("createProjecktasTeam").addID(taskid).build());
+        inventory.setItem(6, new ItemBuilder(Material.PLAYER_HEAD).setHead(player.getDisplayName()).setDisplayName("Create as User").setLore(createAsUserlore()).setGui(true).addIdentifier("createProjecktasUser").addID(taskid).build());
+
+    }
+    public void WorldtypSelect(Player player) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 18]
```diff
@@ -0,0 +1,193 @@
...
+            if(slot < 15||slot>18||slot<24)
+                inventory.setItem(slot, new ItemBuilder(Material.PAPER).setDisplayName((ChatColor.RED + worldType.getString("name"))).setLore("Select " + worldType.getString("name")).setGui(true).addIdentifier(worldType.getString("name")).build());
+
+
+            }
+    }
+
+
+
+    public ArrayList<String> PluginSelector() {return PluginSelector();}
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 19]
```diff
@@ -0,0 +1,193 @@
...
+
+    public void Switch(Inventory inventory,String tag,Boolean Default,Boolean Switch,int Slot){
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java [hunk 20]
```diff
@@ -0,0 +1,193 @@
...
+                    if (PluginSelector().get(i) == tag)
+                        PluginSelector().remove(i);
+                }
+            }
+        }
+    }
+
+
+    @EventHandler
+    public void ClickEvent(InventoryClickEvent event) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TaskGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java [hunk 21]
```diff
@@ -0,0 +1,186 @@
...
+    //Lore list für BS_gui
+    public ArrayList<String> TeamloreList() {
+        ArrayList<String> loreList = new ArrayList<>();
+        loreList.add(ChatColor.GOLD + "--------------");
+        loreList.add(ChatColor.GOLD + "Open Team Menu");
+        loreList.add(ChatColor.GOLD + "--------------");
+        return loreList;
+    }
+
+    public void TeamGui(Player player) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java [hunk 22]
```diff
@@ -0,0 +1,186 @@
...
+
+public class TeamGui implements Listener {
+
+    HeadDatabaseAPI api = new HeadDatabaseAPI();
+    Translation t = Main.getTranslation();
+
+    BuilderSystem builderSystem = Main.getBuilderSystem();
+
+    //Lore list für BS_gui
+    public ArrayList<String> TeamloreList() {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java [hunk 23]
```diff
@@ -0,0 +1,186 @@
...
+        if (team.length() >= 0) {
+            inventory.setItem(16, new ItemBuilder(Material.PAPER).setGui(true).addIdentifier("invite_list_Opener").setDisplayName(ChatColor.GRAY + "Invites List").build());
+            inventory.setItem(13, new ItemBuilder(Material.PAPER).setGui(true).addIdentifier("list_projecks").setDisplayName(ChatColor.GRAY + "Projeckt List").build());
+            inventory.setItem(10, new ItemBuilder(Material.PAPER).setGui(true).addIdentifier("team_manager").setDisplayName(ChatColor.GRAY + "Team Manager").build());
+            inventory.setItem(size - 1, backtoMain);
+        }
+        player.openInventory(inventory);
+    }
+
+    public void TeamInvite(Player player) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java [hunk 24]
```diff
@@ -0,0 +1,186 @@
...
+
+        inventory.setItem(size - 1, backtoTeam);
+        player.openInventory(inventory);
+    }
+
+    public String TeamName;
+    public String TeamDesc;
+    public AnvilGUI anvilgui;
+
+    public void TeamCreatename(Player player) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java [hunk 25]
```diff
@@ -0,0 +1,186 @@
...
+                        TeamCreateDesc(player, output);
+                    }
+                    return AnvilGUI.Response.close();
+                }))
+                .itemLeft(new ItemBuilder(Material.PAPER).setDisplayName("Team Name").build())
+
+                .title(ChatColor.GREEN + "Team Name(PflichtFeld)").plugin(Main.getPlugin()).text("Dein Team Heist").open(player);
+    }
+
+    public void TeamCreateDesc(Player player, String teamName) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/TeamGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java [hunk 26]
```diff
@@ -0,0 +1,193 @@
...
+
+public class WorldGui {
+
+
+    HeadDatabaseAPI api = new HeadDatabaseAPI();
+    Translation t = Main.getTranslation();
+
+    BuilderSystem builderSystem = Main.getBuilderSystem();
+
+    public ArrayList<String> WorldloreList() {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java [hunk 27]
```diff
@@ -0,0 +1,193 @@
...
+        ArrayList<String> loreList = new ArrayList<>();
+        loreList.add(ChatColor.GOLD + "-----------------");
+        loreList.add(ChatColor.GOLD + "Open Project Menu");
+        loreList.add(ChatColor.GOLD + "-----------------");
+        return loreList;
+    }
+
+    public void WorldGui(Player player) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java [hunk 28]
```diff
@@ -0,0 +1,193 @@
...
+        Inventory inventory = Bukkit.createInventory(null, size, (ChatColor.GOLD + "Projeckt Gui"));
+        inventory.setItem(10, WorldListAll);
+        inventory.setItem(16, WorldListUser);
+
+
+        inventory.setItem(size - 1, backtoMain);
+        player.openInventory(inventory);
+    }
+
+    public void WorldListAll(Player player, int index) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java]: @Feier68 please assign functions in camelCase!

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java [hunk 29]
```diff
@@ -0,0 +1,193 @@
...
+        ItemStack backtoTask = new ItemBuilder(api.getItemHead("9334")).setDisplayName((ChatColor.RED + "To World Menu")).setLore((ChatColor.AQUA + "Back to World Gui")).setGui(true).addIdentifier("World_Opener").build();
+
+        Inventory inventory = Main.getWorldCache().getInventory(index);
+
+        int size = 9 * 6;
+        inventory.setItem(size - 1, backtoTask);
+        player.openInventory(inventory);
+    }
+
+    public  void WorldListUser(Player player,int index) {
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java]: @Feier68 please assign functions in camelCase!

**Review by kevinxdev — COMMENTED** [review]
have fun 😄

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java [hunk 30]
```diff
@@ -0,0 +1,184 @@
...
+        JSONArray teams = world.getJSONArray("team_ids");
+
+        for (int j = 0; j < teams.length(); j++) {
+            JSONObject team = teams.getJSONObject(j);
+            String teamname = team.getString("name");
+            StringBuilder res = new StringBuilder();
+            res.append(ChatColor.GRAY + "");
+            res.append(teamname).append("" + ChatColor.WHITE + " , " + ChatColor.GRAY + "");
+
+            res.toString();
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java:154]: @Feier68 not needed

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java [hunk 31]
```diff
@@ -0,0 +1,184 @@
...
+            JSONObject user = users.getJSONObject(j);
+
+            Player player11 = Bukkit.getPlayer(user.getString("name"));
+            String player21 = player11.toString();
+            StringBuilder res1 = new StringBuilder();
+            res1.append(ChatColor.GRAY + "");
+            res1.append(player21).append(ChatColor.WHITE + " , " + ChatColor.GRAY);
+
+
+            res1.toString();
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/Guis/WorldGui.java:174]: @Feier68 not needed

File: src/main/java/net/gigaclub/buildersystemplugin/Andere/InterfaceAPI/ItemBuilder.java [hunk 32]
```diff
@@ -0,0 +1,180 @@
...
+    }
+
+    public ItemBuilder setGui(Boolean is_Gui) {
+        ItemMeta meta = getItemMeta();
+        if (is_Gui == true) {
+            PersistentDataContainer data = meta.getPersistentDataContainer();
+            data.set(new NamespacedKey(Main.getPlugin(), "gui"), PersistentDataType.INTEGER, 1);
+            setItemMeta(meta);
+
+            return this;
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Andere/InterfaceAPI/ItemBuilder.java:170]: @Feier68 not needed

File: src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java [hunk 33]
```diff
@@ -87,65 +90,56 @@ public boolean onCommand(CommandSender sender, Command command, String label, St
...
-                        for (int i = 0; i < allTasks.length(); i++) {
-                            JSONObject taskObject = (JSONObject) allTasks.get(i);
-                            int Taskid = taskObject.getInt("id");
-                            if (Taskid == Integer.parseInt(args[1])) {
-                                JSONObject task = builderSystem.getTask(Taskid);
-                                String TaskName = task.getString("name");
-                                getLogger().info("Taskname: " + TaskName);
-                                builderSystem.createWorldAsUser(playerUUID, Integer.parseInt(args[1]), TaskName, "default");
-                                player.sendMessage(ChatColor.GREEN + t.t("BuilderSystem.world.create_team_succses", playerUUID));
+                        JSONObject task = builderSystem.getTask(Integer.getInteger(args[2]));
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Commands/Worlds.java:93]: @Feier68 Integer.getInteger with Integer.parseInt

File: src/main/java/net/gigaclub/buildersystemplugin/Main.java [hunk 34]
```diff
@@ -109,69 +76,162 @@ public static void setPlugin(Main plugin) {
...
+        ));
+    }
+
+    public static void setBuilderSystem(BuilderSystem builderSystem) {
+        Main.builderSystem = builderSystem;
+    }
+
+    @Override
+    public void onEnable() {
+        plugin = this;
```
Comment (kevinxdev) [inline src/main/java/net/gigaclub/buildersystemplugin/Main.java:172]: @Feier68 not needed

**Comment by kevinxdev** [comment]
Info: I will rework the org.json.JSON... to com.google.gson.Json... because this is better for the future.
